/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_store_free: (a: number, b: number) => void;
export const store_new: () => number;
export const store_process_message: (a: number, b: number, c: number) => [number, number, number, number];
export const __wbg_eventemitter_free: (a: number, b: number) => void;
export const eventemitter_new: () => number;
export const eventemitter_on: (a: number, b: number, c: number, d: any) => any;
export const eventemitter_off: (a: number, b: number, c: number, d: any) => void;
export const eventemitter_emit: (a: number, b: number, c: number, d: any) => void;
export const save_data: (a: number, b: number, c: number, d: number, e: number, f: number, g: any) => any;
export const load_data: (a: number, b: number, c: number, d: number, e: number, f: number) => any;
export const main: () => void;
export const __wbg_wasmbindgentestcontext_free: (a: number, b: number) => void;
export const wasmbindgentestcontext_new: () => number;
export const wasmbindgentestcontext_args: (a: number, b: number, c: number) => void;
export const wasmbindgentestcontext_run: (a: number, b: number, c: number) => any;
export const __wbgtest_console_log: (a: any) => void;
export const __wbgtest_console_debug: (a: any) => void;
export const __wbgtest_console_info: (a: any) => void;
export const __wbgtest_console_warn: (a: any) => void;
export const __wbgtest_console_error: (a: any) => void;
export const __wbgtest_cov_dump: () => [number, number];
export const __externref_table_alloc: () => number;
export const __wbindgen_export_1: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_export_6: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const closure1123_externref_shim: (a: number, b: number, c: any) => void;
export const closure1141_externref_shim: (a: number, b: number, c: any, d: number, e: any) => void;
export const closure1145_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
